[package]
version = "0.1.0"
title = "Robot Learning SDG"
description = "Isaac Sim 5.1 robot camera dataset tutorial"
category = "Examples"

[dependencies]
"omni.ui" = {}
"omni.kit.viewport.utility" = {}
"isaacsim.core.api" = {}
"isaacsim.robot.wheeled_robots" = {}
"isaacsim.sensors.camera" = {}
"omni.replicator.core" = {}

[[python.module]]
name = "robot_sdg"
path = "../../core"

[[python.module]]
name = "robot_sdg_ui"
