"""Package a real Occupancy Map UI export as map.yaml + map.png."""
import argparse
from pathlib import Path
import shutil
import math


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--yaml", required=True, type=Path, help="Saved YAML text from Occupancy Map UI")
    parser.add_argument("--image", required=True, type=Path, help="The PNG actually generated by that UI")
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    import yaml
    metadata = yaml.safe_load(args.yaml.read_text())
    if not isinstance(metadata, dict):
        raise ValueError("Map YAML must be a mapping")
    resolution = metadata.get("resolution")
    origin = metadata.get("origin")
    if not isinstance(resolution, (int, float)) or not math.isfinite(resolution) or resolution <= 0:
        raise ValueError("Map resolution must be a positive meters/pixel number")
    if not isinstance(origin, list) or len(origin) != 3 or not all(isinstance(v, (int, float)) and math.isfinite(v) for v in origin):
        raise ValueError("Map origin must contain x, y, yaw")
    if args.image.read_bytes()[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError("Expected actual exported PNG image")
    target = args.output.expanduser().resolve()
    target.mkdir(parents=True, exist_ok=False)
    metadata["image"] = "map.png"
    (target / "map.yaml").write_text(yaml.safe_dump(metadata, sort_keys=False))
    shutil.copyfile(args.image, target / "map.png")
    print(target / "map.yaml")


if __name__ == "__main__":
    main()
